# Generated by Django 5.0.3 on 2024-04-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_bookinstance_bookstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(help_text='Загрузите изображение автора', null=True, upload_to='author_images/', verbose_name='Изображение автора'),
        ),
    ]
